// The code you need to submit to educoder.
// Edit it educoder's built-in editor.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Generated by codevar_generator, or write manually.
const char cppcode[] =
    "#include <cstdio>\n"
    "#include <cstdlib>\n"
    "// your cpp code, edit in IDE...\n"
    "\n"
    "#include <iostream>\n"
    "\n"
    "int main() {\n"
    "    freopen(\"fr.in\", \"r\", stdin);\n"
    "    int a, b;\n"
    "    std::cin >> a >> b;\n"
    "    std::cout << a + b << '\n';\n"
    "    return 0;\n"
    "}\n"
;

int main() {
    // If test, you need may need use freopen() to stdin to simulate OnlineJudge situation.
    // freopen("test.in", "r", stdin);

    // write "input file" to fr.in through stdin
    FILE *fr = fopen("fr.in", "w");
    char ch;
    while(~(ch = getchar())) putc(ch, fr);
    fclose(fr);

    // Write cpp code to fc.cpp and compile
    FILE* fc = fopen("fc.cpp", "w");
    fprintf(fc, cppcode);
    fclose(fc);
    system("g++ fc.cpp -o fc");
    
    // Get running result from pipe
    FILE* fp = popen("fc", "r");
    char buffer[1024] = "";
    char result[4096] = "";
    while(fgets(buffer, sizeof(buffer), fp) != NULL) {
        strcat(result, buffer);
    }
    puts(result);
    pclose(fp);

	return 0;
}
