import os

# Generated by codevar_generator, or write manually.
cppcode = """
#include <cstdio>\n
#include <cstdlib>\n
// Your cpp code, edit in IDE...\n
\n
#include <iostream>\n
\n
int main() {\n
    freopen(\"fr.in\", \"r\", stdin);\n
    int a, b;\n
    std::cin >> a >> b;\n
    std::cout << a + b << \'\\n\';\n
    return 0;\n
}\n
"""

# write "input file" to fr.in through stdin
os.system("cp /dev/stdin fr.in")

# Write cpp code to fc.cpp and compile
with open("fc.cpp", "w") as fc:
    fc.write(cppcode)
os.system("g++ fc.cpp -o fc")

# Get running result from pipe
with os.popen("fc", "r") as fp:
    result = fp.read()
    print(result, end="")